name: Build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Actions
        uses: actions/checkout@v2

      - name: Set up Deno
        uses: denoland/setup-deno@v1.0.0
        with:
          deno-version: v1.14.0

      - name: Analyze code
        run: deno lint --unstable --config deno.json

      - name: Unit testing
        run: deno test --allow-all --unstable --import-map './test.json' ut/
        