name: Build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Actions
        uses: actions/checkout@v2

      - name: Set up Deno
        uses: denoland/setup-deno@v1.0.0
        with:
          deno-version: v1.14.0

      - name: Analyze code
        run: deno lint --unstable --config deno.json

      - name: Unit testing
        run: |  #Run Like this to not run db.test.js
          deno test --allow-all --unstable --import-map './test.json' ut/businessLayer.test.js            
          deno test --allow-all --unstable --import-map './test.json' ut/generalLogic.test.js
          deno test --allow-all --unstable --import-map './test.json' ut/ORM.test.js
      
      #Run only on master and on push 
      #https://kevsoft.net/2020/06/10/running-github-action-steps-and-jobs-only-on-push-to-master.html
      - if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        #Deploy to heroku
        #https://github.com/marketplace/actions/deploy-to-heroku
        name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          buildpack: https://github.com/chibat/heroku-buildpack-deno.git        